=== mdandotiya/DataModellingRep/Professors.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.iiitb.ac.in"
    xmlns="http://www.iiitb.ac.in"
    elementFormDefault="qualified">
  <xs:element name="Professors" type="ProfessorsType"/>
  <xs:complexType name="NameType">
    <xs:sequence>
      <xs:element type="xs:string" name="FirstName"/>
      <xs:element type="xs:string" name="MiddleName"/>
      <xs:element type="xs:string" name="LastName"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="profileType">
    <xs:sequence>
      <xs:element type="xs:string" name="Experience"/>
      <xs:element type="xs:string" name="ResearchArea" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OfficeAddressType">
    <xs:sequence>
      <xs:element type="xs:string" name="Building"/>
      <xs:element type="xs:byte" name="Floor"/>
      <xs:element type="xs:short" name="Room"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProfessorType">
    <xs:sequence>
      <xs:element type="xs:string" name="Designation"/>
      <xs:element type="NameType" name="Name"/>
      <xs:element type="xs:string" name="Education"/>
      <xs:element type="profileType" name="profile"/>
      <xs:element type="OfficeAddressType" name="OfficeAddress"/>
      <xs:element type="xs:string" name="Email"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProfessorsType">
    <xs:sequence>
      <xs:element type="ProfessorType" name="Professor"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== mdandotiya/DataModellingRep/Professors.xml
<?xml version="1.0" encoding="UTF-8"?>
<Professors xmlns="http://www.iiitb.ac.in"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.iiitb.ac.in Professors.xsd">
    <Professor>
        <Designation>Professor</Designation>
        <Name>
            <FirstName>Chandrashekar</FirstName>
            <MiddleName></MiddleName>
            <LastName>Ramanathan</LastName>
        </Name>
        <Education>PhD from Mississippi State University</Education>
        <profile>
            <Experience>
                Professor Chandrashekar Ramanathan is a faculty member at IIITB since 2007. His primary focus area is data science, software engineering and application development. Professor Chandrashekar received his Ph.D degree from Mississippi State University. His thesis was in the area of object-oriented databases. He has extensive application software development experience spanning over 10 years in large multinational organizations. His current focus is in the area of information convergence and software engineering. Technology for education, Application architectures, enterprise architecture and content management are his other areas of interest.
            </Experience>
            <ResearchArea>Data Science</ResearchArea>
            <ResearchArea>Software Architecture</ResearchArea>
            <ResearchArea>Software Engineering</ResearchArea>
        </profile>
        <OfficeAddress>
            <Building>Aryabhatt Block</Building>
            <Floor>2</Floor>
            <Room>204</Room>
        </OfficeAddress>
        <Email>rc@iiitb.ac.in</Email>
    </Professor>
</Professors>
